pybind11_add_module(og_rl_interface MODULE)
set_target_properties(og_rl_interface PROPERTIES OUTPUT_NAME og_env)
target_link_libraries(og_rl_interface PRIVATE overgrowth_core bullet::bullet pybind11::embed pybind11::python spdlog::spdlog)
target_compile_definitions(og_rl_interface PRIVATE OG_RL_BUILD)
target_compile_options(og_rl_interface PRIVATE /utf-8)
target_include_directories(og_rl_interface PRIVATE ${CMAKE_CURRENT_SOURCE_DIR} ${pybind11_INCLUDE_DIR} ${CMAKE_CURRENT_SOURCE_DIR}/../../Libraries/spdlog/include)
if(UNIX)
    set_target_properties(og_rl_interface PROPERTIES LINK_FLAGS "-Wl,--no-undefined")
endif()