@ECHO OFF
SETLOCAL

SET BUILD_DIR=BuildRelease64
SET BUILD_TARGET_PATH=%~dp0..\%BUILD_DIR%

IF NOT EXIST "%BUILD_TARGET_PATH%" MKDIR "%BUILD_TARGET_PATH%"

PUSHD "%BUILD_TARGET_PATH%"
cmake ../Projects -G "Visual Studio 17 2022" -A x64
CD ..
cmake --build "%BUILD_DIR%" --config Release
POPD

ECHO done
